services:
  influxdb:
    image: influxdb:1.8.10
    container_name: influxdb
    ports:
      - "8086:8086"
    networks:
      - solarnet
    environment:
      - INFLUXDB_DB=db0
      - INFLUXDB_HTTP_FLUX_ENABLED=true
      - INFLUXDB_ADMIN_USER=${INFLUXDB_ADMIN_USER}
      - INFLUXDB_ADMIN_PASSWORD=${INFLUXDB_ADMIN_PASSWORD}
    volumes:
      - ./influxdb-data:/var/lib/influxdb
    restart: always

  chronograf:
    image: chronograf:latest
    container_name: chronograf
    ports:
      - "8888:8888"
    depends_on:
      - influxdb
    environment:
      - INFLUXDB_URL=http://influxdb:8086
      - INFLUXDB_ADMIN_USER=${INFLUXDB_ADMIN_USER}
      - INFLUXDB_ADMIN_PASSWORD=${INFLUXDB_ADMIN_PASSWORD}
    networks:
      - solarnet
    links:
      - influxdb
    volumes:
      - ./chronograf-data:/var/lib/chronograf
    restart: always

  telegraf:
    image: telegraf:latest
    container_name: telegraf
    ports:
      - "8081:8081"
      - "8082:8082"
      - "9100:9100"
      - "9101:9101"
      - "9102:9102"
      - "9200:9200"
      - "9201:9201"
      - "9202:9202"
    networks:
      - solarnet
    links:
      - influxdb
    volumes:
      - ./telegraf.conf:/etc/telegraf/telegraf.conf
    restart: always

  grafana:
    image: grafana/grafana:8.4.3-armv7
    container_name: grafana
    user: "0"
    ports:
      - "9004:3000"
    environment:
      - GF_SERVER_PROTOCOL=https
      - GF_SERVER_PORT=3000
      - GF_SERVER_DOMAIN=${GF_SERVER_DOMAIN}
      - GF_SERVER_ENFORCE_DOMAIN=true
      - GF_SERVER_ROOT_URL=${GF_SERVER_ROOT_URL}
      - GF_SERVER_CERT_KEY=/etc/certs/privkey.pem
      - GF_SERVER_CERT_FILE=/etc/certs/fullchain.pem
    networks:
      - solarnet
    links:
      - influxdb
    volumes:
      - ./grafana-data:/var/lib/grafana
      - ./.certs:/etc/certs
    restart: always

networks:
  solarnet:
